baseURL = "https://ethicalsource.dev"
languageCode = "en-us"
title = "Organization for Ethical Source"

DefaultContentLanguage = "en"
hasCJKLanguage = true
EnableMissingTranslationPlaceholders = true

uglyURLs = false

disableHugoGeneratorInject = true

[minify]
  minifyOutput = true

[mediaTypes]
  [mediaTypes."text/markdown"]
    suffixes = ["md"]

[outputs]
  home = ["html", "rss"]
  page = ["html", "rss"]

[markup.goldmark.renderer]
  unsafe = true
